#!/usr/bin/python
#-*- coding: UTF-8 -*-
#Promting People

age = raw_input("How old are you? ")
height = raw_input("How tall are you? ")
weight = raw_input("How much do you weight? ")
print "So, you're %r old, %r tall and %r heavy." % (age, height, weight)

##raw_input() and input()及文件的操作，详细见exercise_10 and exercise_11_file