#!/usr/bin/python
#-*- coding: UTF-8 -*-
#Reding files

from sys import argv  # 导入modules argv
script, filename = argv #参数个数及名字

txt = open(filename) #打开文件

print "Here's your file %r:" % filename #打印文件名字
print txt.read() #打印读入的文件内容


print "Type the filename again:" #打印字符串
file_again = raw_input('> ') #再次输入文件名字

txt_again = open(file_again) #再次读入文件对象，default为r 模式

print txt_again.read() #打印读入的文件内容

txt.close() #关闭打开文件
txt_again() #关闭打开文件

# Excute on Linux Platform

"""
[jason@shadowsocks exercise]$ ./ex15.py ex_sample.txt
Here's your file 'ex_sample.txt':
This is stuff I typed into a file.
It is really cool stuff.
Lots and lots of fun to have in here.

Type the filename again:
> ex_sample.txt
This is stuff I typed into a file.
It is really cool stuff.
Lots and lots of fun to have in here.
"""
