#!/usr/bin/python
#-*- coding: utf-8 -*-
#what's was that
#http://www.runoob.com/python/python-strings.html
"I am 6'2\" tall." #escape  double-quote inside string
'I am 6\'2" tall.' #escape single-quote  inside string

tabby_cat =  "\tI'm tabbed in."
persian_cat = "I'm split\non a line."
backslash_cat = "I'm \\ a \\ cat."

fat_cat = """
I'll do a list:
\t*Cat food
\t*Fishies
\t*Catnip\n\t* Grass
"""

fat_cat_01 ='''
I'll do a list:
\t*Cat food
\t*Fishies
\t*Catnip\n\t*Grass
'''
fat_cat_02 = "I'll do a list:\n\t*Cat food\n\t*Fishies\n\t*Catnip\n\t*Grass"
fat_cat_03 = 'I will do a list:\n\t*Cat food\n\t*Fishies\n\t*Catnip\n\t*Grass'

print "%s" % tabby_cat
print "%r" % tabby_cat
print persian_cat
print backslash_cat
print fat_cat
print fat_cat_01
print fat_cat_02
print fat_cat_03
print 'I am handsome boy\n and she is so nice' #there is no big difference between double-quotes and sigle quote  with escape string
#while True:
# for i in ["/", "-", "|", "\\", "|"]:
#    print "%s\r" % i

