#!/usr/bin/python
#-*- coding: utf-8 -*-
#More printing

print "Mary  had a little lamb."  #print strings

print "Its fleece was white as %s." % 'snow' #print strings wiht inside variable string

print "And everywhere that Mary went." #print strings

print  "." * 10 # what'd that do? # print ten *

end1 = "C" #define variable end1

end2 = "h" #define varialbe end2

end3 = "e" #define varialbe end3

end4 = "e" #define variable end4

end5 = "s" #define variable end5

end6 = "e" #define variable end6

end7 = "B" #define variable end7

end8 = "u" #define variable end8

end9 = "r" #define variable end9

end10 = "g" #define variable end10

end11 = "e" #define variable end11

end12 = "r" #define vaiable end12

# watch that comma at the end.try removing it to see what happens

print end1 + end2 + end3 + end4 + end5 + end6, #print info with strings stitching end1~en6
print end7 + end8 + end9 + end10 + end11 + end12 #print infor with strings stitching end7=12

'''
Study Drills
Go back through and write a comment on what each line does.
Read each one backward or out loud to find your errors.
From now on, when you make misstakes, write down on a piece of paper what kind of mistake you make.
when you go to next exercise, look at the mistakes you have made and try not to make them in the new one.
Remember that everyone makes mistakes. Programmers are like magicians who fool everyone into thinking they
are perfect and never wrong, but it's all an act, they make mistakes all the time.
'''