#!/usr/bin/python
#-*- coding: UTF-8 -*-
#Functions Can Return Something

"""
add: 加
subtract: 减
multipy: 乘
divide: 除
C:\Users\chehaiyu\Documents\GitHub\Python_practise_Hard_Way
"""
def add(a, b):
    print "ADDING %d + %d" % (a, b)
    return a + b

def substract(a, b):
    print "SUBSTRACT %d - %d" % (a, b)
    return a - b

def multipy(a, b):
    print "MUTIPY  %d * %d" % (a, b)
    return  a * b

def divide(a, b):
    print "DIVIDE %d / %d" % (a, b)
    return a / b

print "Let's do some math with just functions"

age = add(30, 5)
height = substract(78, 4)
weight = multipy(90, 2)
iq  =  divide(100, 2)

print "Age: %d, Height: %d, Weight: %d, IQ: %d" % (age, height, weight, iq)

#A puzzle for the extra credit, type it in anyway.
print "Here is a puzzle"

what = add(age, substract(height, multipy(weight, divide(iq, 2))))

print "That becomes: ", what, "Can you do it by hand?"